terms_by_type = {
   'Corporation': ['company', 'incorporation', 'incorporated', 'corporation', 'corp.', 'corp', 'inc',
      '& co.', '& co', 'inc.', 's.p.a.', 'n.v.', 'a.g.', 'ag', 'a. g.', 'ag.', 'aktiengesellschaft', 'nuf', 's.f.',
      'oao', 'co.', 'co'
   ],
   'General Partnership': ['soc.col.', 'stg', 'd.n.o.', 'ltda.', 'v.o.s.', 'a spol.',
      u've\xc5\x99. obch. spol.', 'kgaa', 'o.e.', 's.f.', 's.n.c.', 's.a.p.a.', 'j.t.d.',
      'v.o.f.', 'sp.j.', 'og', 'sd', ' i/s', 'ay', 'snc', 'oe', 'bt.', 's.s.', 'mb',
      'ans', 'da', 'o.d.', 'hb', 'pt'
   ],
   'Joint Stock / Unlimited': ['unltd', 'ultd', 'sal', 'unlimited', 'saog', 'saoc', 'aj',
      'yoaj', 'oaj', 'akc. spol.', 'a.s.'
   ],
   'Joint Venture': ['esv', 'gie', 'kv.', 'qk'],
   'Private Limited': ['c.a.', 'ca', 'limitada', 'co. ltd.', 's.a', 'pty. ltd.', 'ltd.', 'pty ltd', 'ltd', 'l.t.d.', 'bvba', 'd.o.o.', 'ltda', 'gmbh',
      'g.m.b.h', 'kft.', 'kht.', 'zrt.', 'ehf.', 's.a.r.l.', 'd.o.o.e.l.', 's. de r.l.',
      'b.v.', 'tapui', 'sp. z.o.o.', 's.r.l.', 's.l.', 's.l.n.e.', 'ood', 'oy', 'rt.',
      'teo', 'uab', 'scs', 'sprl', 'limited', 'bhd.', 'sdn. bhd.', 'sdn bhd', 'as',
      'lda.', 'tov', 'pp'
   ],
   'Public Limited': ['pllc', 'llc', 'l.l.c.', 'plc.', 'plc', 'hf.', 'oyj',
      'a.e.', 'nyrt.', 'p.l.c.', 'sh.a.', 'sociedad anonima', 's.a.', 's. a', 's. a.', 's.r.l.', 'srl.', 'aat', '3at', 'd.d.',
      's.r.o.', 'spol. s r.o.', 's.m.b.a.', 'smba', 'sarl', 'nv', 'sa', 'aps',
      'a/s', 'p/s', 'sae', 'sasu', 'eurl', 'ae', 'cpt', 'as', 'ab', 'asa', 'ooo', 'dat',
      'vat', 'zat', 'mchj', 'a.d.'
   ],
   'Limited Liability Limited Partnership': ['lllp', 'l.l.l.p.'],
   'Limited Liability Partnership': ['llp', 'l.l.p.', 'sp.p.', 's.c.a.', 's.c.s.'],
   'Limited Partnership': ['gmbh & co. kg', 'gmbh & co. kg', 'lp', 'l.p.', 's.c.s.',
      's.c.p.a', 'comm.v', 'k.d.', 'k.d.a.', 's. en c.', 'e.e.', 's.a.s.', 's. en c.',
      'c.v.', 's.k.a.', 'sp.k.', 's.cra.', 'ky', 'scs', 'kg', 'kd', 'k/s', 'ee', 'secs',
      'kda', 'ks', 'kb','kt'
   ],
   'Mutual Fund': ['sicav'],
   'No Liability': ['nl'],
   'Non-Profit': ['vzw', 'ses.', 'gte.', 'foundation', 'fundacion', 'charitable'],
   'Private Company': ['private', 'pte', 'pte.', 'xk'],
   'Professional Corporation': ['p.c.', 'vof', 'snc'],
   'Professional Limited Liability Company': ['pllc', 'p.l.l.c.'],
   'Sole Proprietorship': ['e.u.', 's.p.', 't:mi', 'tmi', 'e.v.', 'e.c.', 'et', 'obrt',
      'fie', 'ij', 'fop', 'xt'
   ]
}

terms_by_country = {
   'Albania': ['sh.a.', 'sh.p.k.'],
   'Argentina': ['s.a.', 's.r.l.', 's.c.p.a', 'scpa', 's.c.e i.', 's.e.', 's.g.r',
      'soc.col.'
   ],
   'Australia': ['nl', 'pty. ltd.', 'pty ltd'],
   'Austria': ['e.u.', 'stg', 'gesbr', 'a.g.', 'ag', 'og', 'kg', 'aktiengesellschaft'],
   'Belarus': ['aat', '3at'],
   'Belgium': ['esv', 'vzw', 'vof', 'snc', 'comm.v', 'scs', 'bvba', 'sprl', 'cbva',
      'cvoa', 'sca', 'sep', 'gie'
   ],
   'Bosnia / Herzegovina': ['d.d.', 'a.d.', 'd.n.o.', 'd.o.o.', 'k.v.', 's.p.'],
   'Brazil': ['ltda', 's.a.', 'pllc', 'ad', 'adsitz', 'ead', 'et', 'kd', 'kda', 'sd'],
   'Bulgaria': ['ad', 'adsitz', 'ead', 'et', 'kd', 'kda', 'sd'],
   'Cambodia': ['gp', 'sm pte ltd.', 'pte ltd.', 'plc ltd.', 'peec', 'sp'],
   'Canada': ['gp', 'lp', 'sp'],
   'Chile': ['eirl', 's.a.', 'sgr', 's.g.r.', 'ltda', 's.p.a.', 'sa', 's. en c.',
      'ltda.'
   ],
   'Columbia': ['s.a.', 'e.u.', 's.a.s.', 'suc. de descendants', 'sca'],
   'Croatia': ['d.d.', 'd.o.o.', 'obrt'],
   'Czech Republic': ['a.s.', 'akc. spol.', 's.r.o.', 'spol. s r.o.', 'v.o.s.', u've\xc5\x99. obch. spol.', 'a spol.', 'k.s.', 'kom. spol.', 'kom. spol.'],
   'Denmark': ['i/s', 'a/s', 'k/s', 'p/s', 'amba', 'a.m.b.a.', 'fmba', 'f.m.b.a.', 'smba',
      's.m.b.a.', 'g/s'
   ],
   'Dominican Republic': ['c. por a.', 'cxa', 's.a.', 's.a.s.', 'srl.', 'eirl.', 'sa',
      'sas'
   ],
   'Ecuador': ['s.a.', 'c.a.', 'sa', 'ep'],
   'Egypt': ['sae'],
   'Estonia': ['fie'],
   'Finland': ['t:mi', 'tmi', 'as oy', 'as.oy', 'ay', 'ky', 'oy', 'oyj', 'ok'],
   'France': ['sicav', 'sarl', 'sogepa', 'ei', 'eurl', 'sasu', 'fcp', 'gie', 'sep', 'snc',
      'scs', 'sca', 'scop', 'sem', 'sas'
   ],
   'Germany': ['gmbh & co. kg', 'gmbh & co. kg', 'e.g.', 'e.v.', 'gbr', 'ohg', 'partg',
      'kgaa', 'gmbh', 'g.m.b.h.', 'ag', 'aktiengesellschaft'
   ],
   'Greece': ['a.e.', 'ae', 'e.e.', 'ee', 'epe', 'e.p.e.', 'mepe', 'm.e.p.e.', 'o.e.',
      'oe', 'ovee', 'o.v.e.e.'
   ],
   'Guatemala': ['s.a.', 'sa'],
   'Haiti': ['sa'],
   'Hong Kong': ['ltd', 'unltd', 'ultd', 'limited'],
   'Hungary': ['e.v.', 'e.c.', 'bt.', 'kft.', 'kht.', 'kkt.', 'k.v.', 'zrt.', 'nyrt',
      'ev', 'ec', 'rt.'
   ],
   'Iceland': ['ehf.', 'hf.', 'ohf.', 's.f.', 'ses.'],
   'India': ['pvt. ltd.', 'ltd.', 'psu', 'pse'],
   'Indonesia': ['ud', 'fa', 'pt'],
   'Ireland': ['cpt', 'teo'],
   'Israel': ['b.m.', 'bm', 'ltd', 'limited'],
   'Italy': ['s.n.c.', 's.a.s.', 's.p.a.', 's.a.p.a.', 's.r.l.', 's.c.r.l.', 's.s.'],
   'Latvia': ['as', 'sia', 'ik', 'ps', 'ks'],
   'Lebanon': ['sal'],
   'Lithuania': ['uab', 'ab', 'ij', 'mb'],
   'Luxemborg': ['s.a.', 's.a.r.l.', 'secs'],
   'Macedonia': ['d.o.o.', 'd.o.o.e.l', 'k.d.a.', 'j.t.d.', 'a.d.', 'k.d.'],
   'Malaysia': ['bhd.', 'sdn. bhd.'],
   'Mexico': ['s.a.', 's. de. r.l.', 's. en c.', 's.a.b.', 's.a.p.i.'],
   'Mongolia': ['xk', 'xxk'],
   'Netherlands': ['v.o.f.', 'c.v.', 'b.v.', 'n.v.'],
   'New Zealand': ['tapui', 'ltd', 'limited'],
   'Nigeria': ['gte.', 'plc', 'ltd.', 'ultd.'],
   'Norway': ['asa', 'as', 'ans', 'ba', 'bl', 'da', 'etat', 'fkf', 'hf', 'iks', 'kf',
      'ks', 'nuf', 'rhf', 'sf'
   ],
   'Oman': ['saog', 'saoc'],
   'Pakistan': ['ltd.', 'pvt. ltd.', 'ltd', 'limited'],
   'Peru': ['sa', 's.a.', 's.a.a.'],
   'Philippines': ['coop.', 'corp.', 'corp', 'ent.', 'inc.', 'inc', 'llc', 'l.l.c.',
      'ltd.'
   ],
   'Poland': ['p.p.', 's.k.a.', 'sp.j.', 'sp.k.', 'sp.p.', 'sp. z.o.o.', 's.c.', 's.a.'],
   'Portugal': ['lda.', 'crl', 's.a.', 's.f.', 'sgps'],
   'Romania': ['s.c.a.', 's.c.s.', 's.n.c.', 's.r.l.', 'o.n.g.', 's.a.'],
   'Russia': ['ooo', 'oao', 'zao', '3ao'],
   'Serbia': ['d.o.o.', 'a.d.', 'k.d.', 'o.d.'],
   'Singapore': ['bhd', 'pte ltd', 'sdn bhd', 'llp', 'l.l.p.', 'ltd.', 'pte'],
   'Slovenia': ['d.d.', 'd.o.o.', 'd.n.o.', 'k.d.', 's.p.'],
   'Slovakia': ['a.s.', 'akc. spol.', 's.r.o.', 'spol. s r.o.', 'k.s.', 'kom. spol.', 'v.o.s.', 'a spol.'],
   'Spain': ['s.a.', 's.a.d.', 's.l.', 's.l.l.', 's.l.n.e.', 's.c.', 's.cra', 's.coop',
      'sal', 'sccl'
   ],
   'Sweden': ['ab', 'hb', 'kb'],
   'Switzerland': ['ab', 'sa', 'gmbh', 'g.m.b.h.', 'sarl', 'sagl'],
   'Turkey': ['koop.'],
   'Ukraine': ['dat', 'fop', 'kt', 'pt', 'tdv', 'tov', 'pp', 'vat', 'zat', 'at'],
   'United Kingdom': ['plc.', 'plc', 'cic', 'cio', 'l.l.p.', 'llp', 'l.p.', 'lp', 'ltd.',
      'ltd', 'limited'
   ],
   'United States of America': ['llc', 'inc.', 'corporation', 'incorporated', 'company',
      'limited', 'corp.', 'inc.', 'inc', 'llp', 'l.l.p.', 'pllc', 'and company',
      '& company', 'inc', 'inc.', 'corp.', 'corp', 'ltd.', 'ltd', '& co.', '& co', 'co.',
      'co', 'lp'
   ],
   'Uzbekistan': ['mchj', 'qmj', 'aj', 'oaj', 'yoaj', 'xk', 'xt', 'ok', 'uk', 'qk']
}

terms_by_industry = { 'Unknown' : ['enterprise', 'enterprises', 'entreprise', 'entreprises',
     'business', 'negocios', 
     'company', 'compania', 'companie', 'cie', '& cie', 'compagnie', 'companhia',
     'continental', 
     'national', 'nacional', 'nationale', 
     'team', 
     'founders', 
     'franchise', 'franchises', 'franquincias',
     'group', 'grupo', 'groupo', 'groupe',
     'service', 'services', 'servicio', 'servicios',
     'venture', 'ventures', 
     'alliance', 'allied',
     'industrial', 
     'associated', 
     'universal',
     'organisation', 'organizacion', 'organisme', 'organismes',
     'societe', 'society', 'sociedad', 'gesellshaft',
     'world',
     'united', 'union', 'unidas'], 
'Accommodation & Food': ['accomodation', 'accomodations',
     'bars', 
     'bistro', 
     'burger', 
     'cafe', 
     'caravan', 
     'cater', 
     'caterers', 'catering', 
     'chef', 
     'chicken', 
     'chippy', 
     'chips', 
     'coffee',  
     'cuisine', 
     'deli', 
     'diner', 'dining', 
     'eat',
     'fish', 
     'food', 'foods',
     'beverage', 'beverages', 'bedidas', 'bedida',
     'fried',  
     'gourmet', 
     'grill', 
     'hospitality', 
     'holidays', 'holiday', 'vacances', 'vacaciones',
     'hotel', 'hotels', 
     'inn', 'inns',
     'kebab',
     'kitchen',
     'leisure',
      'lounge',
      'pizza',
      'pizzeria',
      'pub',
      'pubs',
      'restaurant',
      'restaurants',
      'sandwich',
      'spice',
      'sushi',
      'takeaway',
      'tandoori',
      'taste',
      'tasty',
      'taverns',
      'wok'],
 'Extraterritorial organisations': ['biotech', 'biotechnologies', 'biotechnology', 'biological', 
      'corporation', 'corporate', 'corporations', 'corporacion',
      'chancery', 
      'international', 'internationale', 'internacionales', 'internacional', 
      'overseas', 'oversea',
      'global',  
      'establishment', 'establecimiento', 'etablissement',
      'chemical',
      'dormant',
      'fertilizer',
      'industry', 'industria', 'industrie', 'industries',
      'worldwide', 'mundial', 'mondial'],
 'Households as employers': ['association',
      'barns',
      'bath',
      'block',
      'close',
      'croft',
      'drive',
      'flat', 'flats',
      'gardens',
      'gate',
      'grange',
      'heights',
      'high',
      'house',
      'hove',
      'kings',
      'lodge',
      'manor',
      'mansions',
      'meadows',
      'mews',
      'mill',
      'number',
      'orchard',
      'owners',
      'parade',
      'phase',
      'place',
      'priory',
      'queens',
      'resident',
      'residents',
      'tenants',
      'villas',
      'walk',
      'wharf',
      'yard'],
 'Administrative & Support Services': ['agency', 'agencies',
        'admin', 'administration', 'administrations', 'administracion', 'administraciones', 'gestion', 'gestionaire', 'de gestion',
        'alarms',
        'appointments',
        'cctv',
        'clean', 'cleaner', 'cleaning',
        'director', 'directors', 'directorship',
        'executives',
        'secretary', 'secretaries', 'secretarial',
        'employment',
        'facilities', 'facility',
        'gardening',
        'grounds',
        'guarding',
        'hire',
        'hr',
        'investigations',
        'jobs',
        'landscape', 'landscapes', 'landscaping',
        'maid',
        'management', 'managing', 'manager', 'managers',
        'office',
        'outsourcing',
        'people',
        'personnel',
        'placement', 'placements',
        'processing',
        'recruit', 'recruiters', 'recruiting', 'recruitment',
        'search',
        'secure', 'security',
        'selection',
        'service',
        'source',
        'staff', 'staffing',
        'supply',
        'system',
        'tour', 'tours', 'tourism', 'turismo', 'tourist', 'touristique', 
        'travels'],
 'Agriculture, Forestry & Fishing': ['agricultural',
          'agriculture',
          'angling',
          'beef',
          'breeders', 'breeding',
          'carp',
          'cattle',
          'countryside',
          'eggs',
          'equestrian',
          'equine',
          'farm', 'farmers', 'farming', 'farms',
          'firewood',
          'fisheries', 'fishing', 'fish',
          'forest', 'forests', 'forestry', 'reforestation', 'foret',
          'fruits', 
          'genetics',
          'grain',
          'growers',
          'harvesting',
          'horses',
          'kennels',
          'livery',
          'livestock',
          'logging',
          'logs',
          'mushrooms',
          'mussels',
          'oysters',
          'pigs',
          'plants',
          'potatoes',
          'poultry',
          'salads', 'salad',
          'salmon',
          'seeds',
          'sheep',
          'shellfish',
          'stables',
          'straw',
          'stud',
          'surgeons',
          'tree', 'trees',
          'timber', 'timbers',
          'trout',
          'turkeys',
          'vineyard', 'vacation'],
 'Arts, Entertainment & Recreation': ['adventure', 'adventures',
      'artists',
      'art', 'arts',
      'athletic',
      'bowling', 'bowls',
      'boxing',
      'club',
      'dance',
      'entertainment', 'entertainment industry', 'entertainments', 'entretenimiento', 'entretenimientos',
      'escape',
      'event', 'events', 'event mangement',
      'fc',
      'festival', 'festivals',
      'fit', 'fitness', 'crossfit',
      'football',
      'gaming', 'games',
      'golf',
      'gym', 'gymnastics',
      'indoor',
      'league',
      'life', 'lifestyle',
      'museum', 'museums',
      'opera',
      'orchestra',
      'performing', 'performer',
      'personal', 'personal trainer',
      'pilates',
      'play',
      'promotions',
      'racing',
      'rugby',
      'sailing',
      'snooker',
      'soccer',
      'sport', 'sporting', 'sports', 'deportes', 'deporte',
      'stage',
      'strength',
      'theatre', 'theatres', 'cinema', 'cinemas',
      'touring',
      'yoga', 
      'yacht'],
 'Construction': ['bathrooms',
      'build', 'builder', 'builders', 'building', 'buildings', 'constructora', 'constructeur', 
      'carpentry',
      'ceilings',
      'civil',
      'construct', 'construction', 'constructions', 'construcciones',
      'contracting',
      'contractor',
      'contractors',
      'contracts',
      'decor',
      'decorating',
      'decorators',
      'demolition', 
      'develop', 'developers', 'development', 'developments', 'desarrollos', 'desarrollo',
      'doors',
      'electrical', 'electrics',
      'fencing',
      'flooring',
      'gas',
      'groundwork', 'ground work',
      'glazing',
      'heating',
      'improvements',
      'installation',
      'installations',
      'interior',
      'interiors',
      'maintenance',
      'mechanical',
      'painting',
      'paving',
      'plumbing',
      'projects',
      'rail',
      'renovation',
      'renovations',
      'roofing',
      'scaffolding',
      'site',
      'surfacing',
      'structures', 'estructuras', 
      'utilities',
      'windows'],
 'Education': ['academy', 'academic', 'academies',
      'assessment',
      'college', 'colleges',
      'courses',
      'cultural',
      'dyslexia',
      'education', 'educational', 'educate',
      'girls',
      'grammar',
      'institute',
      'kids',
      'language', 'languages',
      'leadership',
      'learn', 'learning',
      'maths',
      'minds',
      'mentoring',
      'nursery',
      'pre',
      'preparatory',
      'preschool',
      'primary', 'primary school',
      'qualifications',
      'school', 'schools', 'schule', 'auslandsschulen', 'ecole', 'ecoles',
      'science',
      'skills',
      'studies', 'study', 'estudios',
      'teach', 'teachers', 'teaching',
      'training', 'schulung', 'capacitacion',
      'tuition', 'tutor', 'tutoring', 'tutors',
      'university', 'universities', 'uni', 'universite', 'universites', 'universidad', 'universidades'],
 'Electricity, Gas & Air Conditioning': ['air conditioning', 
      'climate',
      'dam',
      'electricity',
      'energies', 'energy', 'energia', 'energetica'
      'generation',
      'grid',
      'hydro',
      'peak',
      'power', 'power plant',
      'renewable', 'renewables',
      'reserve',
      'solar',
      'thermal',
      'tidal',
      'transmission',
      'turbine', 'turbines', 'wind turbine', 'wind farm', 
      'utility', 'utilities',
      'wind'],
 'Finance and Insurance': ['advice', 'adviser', 'advisers', 'financial adviser', 'financial advisers', 'asesores', 
      'asset', 'assets', 
      'bank', 'banks', 'banker', 'bankers', 'banque', 'banco', 'bancorp',
      'benefits',
      'broker',
      'brokers',
      'capital', 'capitals',
      'claims',
      'cover',
      'credit', 'credicorp',
      'currency',
      'debt',
      'exchange',
      'finance', 'finances', 'financial', 'financials', 'financing', 'finanz', 'financiare', 'financiera', 'financiero',
      'fund', 'funds', 'funding', 'fond', 'fonds',
      'fiduciary', 'fiduciaries', 'fiducia', 'fiduciaria', 'fiduciaire', 'fiduciaires',
      'fx',
      'holding', 'holdings',
      'income', 'rentas',
      'independent',
      'infrastructure',
      'insurance', 'insure',
      'kasse', 
      'lending',
      'loans', 'loan',
      'markets', 'financial market'
      'member', 'members', 
      'mortgage', 'mortgages',
      'nominee', 'nominees',
      'payment', 
      'pension', 'pensions', 
      'planing', 'financial planning', 
      'protect', 'securities', 'treasury', 
      'trust', 'trusts', 'trustee', 'trustees',
      'wealth', 'wealths',
      'equity', 'equities', 'equitee', 'equitees',
      'investors', 'investor', 'inversora', 'inversionista', 'invest', 'investing', 'investment', 'investments', 'investissement', 'investissements', 'inversiones', 'inversion', 'investimentos',
       'savings', 'spare'],
 'Human Health & Social Work': ['anesthetics', 'anaesthesia',
      'ambulance',
      'biomedical',
      'caring',
      'children',
      'clinic', 'clinical', 'clinics',
      'counselling',
      'cosmetic', 'cosmetics',
      'dental', 'dentist',
      'dr', 'doctor', 'doctors', 'medicos', 'medico',
      'eye',
      'foot',
      'fostering',
      'health', 'health care', 'healthcare', 'sante',
      'hospital', 'hospitals', 
      'hearing',
      'holistic',
      'home', 'domicilio',
      'imaging',
      'laboratory', 'lab', 'labs',
      'med', 'medical', 'medicare',
      'medicine',
      'medics',
      'mental',
      'mind',
      'nursing',
      'occupational',
      'optical', 'optics',
      'physio',
      'pharma', 'pharmaceutical', 'pharmaceuticals',
      'physiotherapy',
      'practice',
      'psychological', 'psychology', 'psychotherapy',
      'radiology',
      'rehabilitation',
      'smile', 'smiles',
      'social',
      'support', 'supported',
      'surgery', 'surgical', 'laser surgery', 'eye surgery',
      'therapies', 'therapy', 'therapist',
      'wellbeing',
      'wellness',
      'work'],
 'Information & Communication': ['agile',
      'app',
      'apps',
      'books',
      'broadcast',
      'cabel',
      'code',
      'com',
      'comms',
      'communications',
      'computer', 'computers', 'computing',
      'connect', 'connection', 'connected',
      'cyber',
      'data',
      'digital',
      'film', 'films',
      'hosting',
      'information', 'information technology', 'it', 'informatica', 'informatique',
      'intelligence',
      'interactive',
      'internet',
      'labs',
      'magazine', 'magazines',
      'media',
      'net',
      'network', 'networks',
      'pictures',
      'pixel',
      'production', 'productions', 'produktion',
      'publication', 'publications', 'publishing', 'publisher',
      'radio',
      'satellite',
      'software', 'softwares',
      'solutions', 'soluciones',
      'studios',
      'systems',
      'tech', 'technologies', 'technology', 'tecnologia', 'technologie',
      'telecom', 'telecommunication', 'telecommunications', 'telekom', 'telecomunicaciones', 'telesystem', 'telesystems', 'telekomunikasi',
      'telephone', 'telephonie', 'telefonia',
      'television', 'tv',
      'video',
      'web', 'web development',
      'wireless'],
 'Manufacturing': [ 'equipment', 
      'products', 'productos',
      'aerospace',
      'aircraft',
      'aluminium',
      'automation',
      'bakery',
      'bespoke',
      'blinds',
      'brewery',
      'brewing',
      'cakes',
      'cider',
      'components',
      'composite',
      'concrete',
      'controls',
      'custom',
      'display',
      'distillery',
      'electronic', 'electronics',
      'engineering',
      'fabrication',
      'factory', 'factories', 'usine', 'usines',
      'finishing',
      'graphics',
      'hydraulics',
      'industries', 'industriales',
      'instruments',
      'labels',
      'lift', 'lifts',
      'laboratories',
      'machine',
      'manufacturing',
      'metal',
      'packaging',
      'plastic',
      'plastics',
      'powder',
      'precision',
      'print', 'printers', 'printing', 'prints',
      'refrigeration',
      'sheet',
      'sign', 'signs',
      'steel', 'stainless steel', 'steel mill', 'steel industry', 'siderurgica', 'siderurgia', 'siderurgie',
      'tool',
      'upholstery',
      'welding'],
 'Mining & Quarrying': ['bp',
      'copper',
      'coal', 'charcoal',
      'crushing',
      'drilling',
      'exploration',
      'fluids',
      'geological',
      'gravel',
      'mine', 'mines', 'mining', 
      'mineral', 'minerals',
      'metals', 'metallhandelgesellshaft',
      'offshore',
      'oil',
      'petrol', 'petroleum', 'petrochemical', 'petroleos',
      'quarries',
      'quarry',
      'reservoir',
      'resources', 'recursos',
      'rig',
      'upstream'
      'zinc'],
 'Other Services': ['appliance',
      'assembly',
      'barbers',
      'barbershop',
      'brow', 'brows',
      'canine',
      'cleaners',
      'confederation',
      'cut', 'cuts',
      'directors',
      'dog','dogs',
      'federation',
      'fellowship',
      'funeral', 'funerals',
      'groom', 'grooming',
      'hair', 'hairdressers', 'hairdressing', 'haircut', 'haircuts',
      'hand',
      'ironing',
      'laser',
      'lashes',
      'laundry',
      'linen',
      'makeup',
      'masonic',
      'massage',
      'memorials',
      'mission',
      'nails',
      'paws',
      'redeemed',
      'retreat',
      'salon', 'salons',
      'scissors',
      'spa',
      'tanning',
      'tattoo',
      'unisex',
      'voluntary'],
 'Scientific & Technical Professions': ['accountancy', 'accountants', 'accounting', 'accounts', 'wirtschaftsdienst',
      'advertising',
      'advisors', 'advisory', 'advisor',
      'attorney',
      'apartment', 'apartments',
      'architects', 'architectural', 'architecture',
      'associates', 'associate', 'associados', 'asociados',
      'audit',
      'bookkeeping',
      'business',
      'change',
      'chartered',
      'compliance',
      'consult', 'consultancy', 'consultant', 'consultants', 'consulting', 'consultora', 'consultores',
      'design',
      'firm', 'court', 'cabinet', 'firma', 
      'innovation',
      'insight',
      'inspection',
      'interim',
      'law', 'lawyer', 'lawyers', 'abvogado', 'abvogados', 'avocat', 'advocate',
      'judge', 'magistrate',
      'legal',
      'liberal', 'profession liberal',
      'marketing',
      'partner', 'partnership', 'partners', ''
      'payroll',
      'photography',
      'pr',
      'process',
      'procurement',
      'project',
      'quantity',
      'relations',
      'representative', 'representatives', 'representation', 'representations', 'representant', 'representant', 'representaciones', 'representacion', 
      'research',
      'scientific',
      'solicitor', 'solicitors',
      'strategic', 'strategy',
      'surveying', 'surveyors', 'surveys', 'survey',
      'tax', 'taxation',
      'technical',
      'translations',
      'veterinary',
      'vets'],
 'Public Administration, Defence & Social Security': ['defence',
      'fire',
      'mist',
      'prison',
      'president',
      'ministries', 'ministry'],
 'Real estate activities': ['abode',
      'agents', 'agent',
      'assets',
      'bricks',
      'buyers',
      'commercial',
      'dwellings',
      'real estate', 'imobiliarios', 'immobiliere', 'immobilier', 'inmobiliario', 'immobilien', 'agence immobiliere', 'inmobiliaria',
      'estate', 'estates', 'raices',
      'homes', 'houses', 'housing', 
      'income trust',
      'keys',
      'land', 'landlord','landmark',
      'let', 'lets', 'letting',
      'living',
      'nest',
      'offices',
      'portfolio', 'portfolios', 'portafolio', 'portafolios',
      'prime',
      'prop', 'properties', 'property', 'propriete', 'proprietes', 'propiedades', 'property management',
      'real', 'realty',
      'relocation',
      'rent', 'rents', 'rental', 'rentals',
      'residency', 'residence', 'residences', 'residential', 'domicilios', 
      'sdi',
      'sourced',
      'space', 'spaces',
      'suites',
      'tenant', 'tenants'],
 'Transportation & Storage': ['navigation', 'airport',
      'aviation',
      'air', 'airline', 'airlines', 'airplane', 'airport', 'aeroport', 
      'bulk',
      'bus', 'buses', 'autobus',
      'cab', 'cabs',
      'cargo', 'cargos', 'cargo ship',
      'carrier', 'carriers',
      'chauffeur',
      'charter',
      'coach', 'coaches',
      'container',
      'courier', 'couriers',
      'cruise', 'cruises',
      'deliveries', 'delivery',
      'drivers', 'driving',
      'express',
      'forwarding',
      'flight', 'flights',
      'freight', 'freighter',
      'line',
      'logistic', 'logistics',
      'maritime', 'maritima', 
      'marine',
      'minibus',
      'movements', 'movers', 'moves', 'moving',
      'parcel', 'parcels',
      'parking',
      'railway',
      'shipping',
      'storage',
      'storehouse',
      'taxi',
      'taxis',
      'trans',
      'transfers',
      'transport', 'transportation', 'transporter', 'transporters', 'transports',
      'trucking'],
 'Water & Waste Management': ['asbestos',
      'cleansing',
      'clear', 'clearances',
      'confidential',
      'disposal', 'dispose'
      'drain', 'drainage', 'drains',
      'environmental',
      'garbage',
      'junk',
      'landfill',
      'metals',
      'reclamation',
      'recycle', 'recycled', 'recycling',
      'reuse',
      'rubbish',
      'sanitation', 'saneamento',
      'sewerage',
      'scrap',
      'shred', 'shredding',
      'skips',
      'suez',
      'treatment',
      'waste', 'waste management', 
      'water', 'water supply'],
 'Wholesale & Retail': ['commodities', 
    'phone', 'mobile phone',
    'commercial', 'commerce', 'comercio', 'comercial', 'commerciale', 'comerciales',
    'accessories',                                                  
    'antiques',
    'apparel',                                       
    'appliances',
    'auto', 'automotive', 
    'boutique',
    'brands',         
    'butchers',
    'carpets',
    'cars',
    'clothing',
    'commercials',
    'convenience',
    'cosmetics',
    'direct',
    'distribution', 'distributors', 'distribuicao', 'distribuidora', 'distribuidoras',
    'export', 'exports',
    'fashion', 'style',
    'flowers',
    'garage',
    'gifts',
    'import', 'imports', 'importadora', 'importer', 'importers',
    'jewellers', 'jewellery',
    'market',
    'meat',
    'mot',
    'motor', 'motors',
    'news',
    'online',
    'parts',
    'pharmacy',
    'repair',
    'repairs',
    'retail',
    'sales', 'ventas', 'vente',
    'shop', 'shopping', 'shopping center',
    'spares',
    'store', 'stores', 'convenience store',
    'supermarket',
    'supplies', 'suppliers', 'supplier',
    'trade', 'trader', 'traders', 'trading',
    'vehicle', 'vehicule', 
    'wholesale',
    'wine', 'wines']}